services/account/app/models.py
from flask_security import UserMixin, RoleMixin
from sqlalchemy import Boolean, DateTime, Column, Integer, \
    String, ForeignKey, UnicodeText
from sqlalchemy.orm import relationship, backref

from services.account.app.database import Base


class RolesUsers(Base):
    __tablename__ = 'roles_users'
    id = Column(Integer(), primary_key=True)
    user_id = Column('user_id', Integer(), ForeignKey('user.id'))
    role_id = Column('role_id', Integer(), ForeignKey('role.id'))


class Role(Base, RoleMixin):
    __tablename__ = 'role'
    id = Column(Integer(), primary_key=True)
    name = Column(String(80), unique=True)
    description = Column(String(255))
    permissions = Column(UnicodeText)


class User(Base, UserMixin):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    email = Column(String(255), unique=True)
    name = Column(String(255), nullable=True)
    username = Column(String(255), unique=True, nullable=True)
    password = Column(String(255), nullable=False)
    last_login_at = Column(DateTime())
    current_login_at = Column(DateTime())
    last_login_ip = Column(String(100))
    current_login_ip = Column(String(100))
    login_count = Column(Integer)
    active = Column(Boolean())
    fs_uniquifier = Column(String(255), unique=True, nullable=False)
    confirmed_at = Column(DateTime())
    roles = relationship('Role', secondary='roles_users',
                         backref=backref('users', lazy='dynamic'))

services/account/app/forms.py
async def validate_login_form(conn, form):
    pass

services/account/app/__init__.py
from flask import Flask
from flask_security import Security, SQLAlchemySessionUserDatastore
from .config import DevelopmentConfig

from .database import db_session, init_db
from .models import User, Role


def create_app():
    app = Flask(__name__)
    app.config.from_object(DevelopmentConfig)
    # Setup Flask-Security
    user_datastore = SQLAlchemySessionUserDatastore(db_session, User, Role)
    app.security = Security(app, user_datastore)
    from .routes import auth as auth_blueprint, user as user_blueprint
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(user_blueprint)
    with app.app_context():
        init_db()
    return app

services/account/app/routes.py
from flask import Blueprint, render_template, request, redirect, flash, url_for, current_app
from flask_security import auth_required, hash_password, utils, login_user, login_required, logout_user, current_user

from services.account.app.models import User
from .database import db_session
from .models import User

auth = Blueprint('auth', __name__, url_prefix='/auth')

user = Blueprint('user', __name__, url_prefix='/user')


@auth.route('/signin')
def signin():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile'))
    return render_template('signin.html')


@auth.route('/signin', methods=['POST'])
def signin_post():
    is_verified = False
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    user = User.query.filter_by(email=email).first()
    if user:
        is_verified = utils.verify_password(password, user.password)
    if not is_verified:
        flash('Неверный логин или пароль')
        return redirect(url_for('auth.signin'))
    login_user(user, remember=remember)
    return redirect(url_for('user.profile'))


@auth.route('/restore_password')
def restore_password():
    return render_template('restore_password.html')


@auth.route('/signup')
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('user.profile'))
    return render_template('signup.html')


@auth.route('/signup', methods=['POST'])
def signup_post():
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    if current_app.security.datastore.find_user(email=email):
        flash('Пользователь уже зарегистрирован, авторизуйтесь')
        return redirect(url_for('auth.signin'))
    user = current_app.security.datastore.create_user(email=email, password=hash_password(password))
    db_session.commit()
    if user:
        flash('Создан новый пользователь, авторизуйтесь')
        return redirect(url_for('auth.signin'))
    return redirect(url_for('auth.signup'))


@user.route('/profile')
@auth_required()
def profile():
    return render_template('profile.html')


@user.route("/")
@auth_required()
def home():
    return redirect(url_for('user.profile'))


@auth.route('/signout', methods=['GET'])
@login_required
def signout():
    logout_user()
    return redirect(url_for('auth.signin')) or request.referrer


@user.route('/users', methods=['GET'])
@login_required
def user_list():
    """
    limit:integer Количество элементов в ответе (по умолчанию равно 20)
    filter[email]:string	Email пользователя
    filter[groups][]: array Группы пользователя
    filter[status]: string Статус пользователя в системе.

    :return:
    """
    args = request.args
    u_limit = args.get("limit", default=20, type=None)
    u_filter = args.get("filter", default=None, type=None)
    if u_filter:
        users = User.query.filter_by().limit(u_limit)
    else:
        users = User.query.limit(u_limit)
    return render_template('user_list.html', users=users)


@user.route('/<int:user_id>', methods=['GET'])
@login_required
def select_user_by_id(user_id):
    find_user = current_app.security.datastore.find_user(id=user_id)
    if find_user:
        return render_template('profile.html', user=find_user)
    return render_template('profile.html', user=find_user)

services/account/app/views.py
async def index(request):
    pass

async def login(request):
    pass

async def logout(request):
    pass

async def register(request):
    pass

services/account/app/templates/base.html
<html lang="en" dir="ltr" data-lt-installed="true">
<head>
    {% block head %}
    <meta charSet="UTF-8">
    <title>{% block title %}{% endblock %} {{ config.PROJECT_NAME|capitalize }}</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/register.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/account.css') }}"/>
    {% endblock head %}
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul class=flashes>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
</head>
<body>
<div id="__next">
    <div class="layout-wrapper MuiBox-root css-33gw4">
        {% block body %}
        {% block header %}
        {% endblock %}
        {% block main %}
        {% endblock %}
        {% block footer %}
        {% endblock %}
        {% endblock body %}
    </div>
</div>
</body>
</html>
{% block javascript %}
{% endblock %}

services/account/app/templates/restore_password.html
{% extends "base.html" %}
{% block title %}Forgot password{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block body %}
<div class="app-content MuiBox-root css-1bguz3s">
    <div class="content-center MuiBox-root css-0">
        <div class="MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-f615w0">
            <div class="MuiCardContent-root css-1m7wlm">
                <div class="MuiBox-root css-1vmv954">
                    <svg width="47" fill="none" height="26" viewBox="0 0 268 150"
                         xmlns="http://www.w3.org/2000/svg">
                        <rect rx="25.1443" width="50.2886" height="143.953" fill="#666CFF"
                              transform="matrix(-0.865206 0.501417 0.498585 0.866841 195.571 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill-opacity="0.4"
                              fill="url(#paint0_linear_7821_79167)"
                              transform="matrix(-0.865206 0.501417 0.498585 0.866841 196.084 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill="#666CFF"
                              transform="matrix(0.865206 0.501417 -0.498585 0.866841 173.147 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill="#666CFF"
                              transform="matrix(-0.865206 0.501417 0.498585 0.866841 94.1973 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill-opacity="0.4"
                              fill="url(#paint1_linear_7821_79167)"
                              transform="matrix(-0.865206 0.501417 0.498585 0.866841 94.1973 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill="#666CFF"
                              transform="matrix(0.865206 0.501417 -0.498585 0.866841 71.7728 0)"></rect>
                        <defs>
                            <linearGradient y1="0" x1="25.1443" x2="25.1443" y2="143.953"
                                            id="paint0_linear_7821_79167" gradientUnits="userSpaceOnUse">
                                <stop></stop>
                                <stop offset="1" stop-opacity="0"></stop>
                            </linearGradient>
                            <linearGradient y1="0" x1="25.1443" x2="25.1443" y2="143.953"
                                            id="paint1_linear_7821_79167" gradientUnits="userSpaceOnUse">
                                <stop></stop>
                                <stop offset="1" stop-opacity="0"></stop>
                            </linearGradient>
                        </defs>
                    </svg>
                    <h6 class="MuiTypography-root MuiTypography-h6 css-fjavz9">{{ config.PROJECT_NAME|capitalize }}</h6></div>
                <div class="MuiBox-root css-97rap9"><h5 class="MuiTypography-root MuiTypography-h5 css-189ky18">
                    Forgot Password? 🔒</h5>
                    <p class="MuiTypography-root MuiTypography-body2 css-19cqx3h">Enter your email and we′ll
                        send you instructions to reset your password</p></div>
                <form novalidate="" autocomplete="off">
                    <div class="MuiFormControl-root MuiTextField-root css-1rlptux"><label
                            class="MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-outlined MuiFormLabel-root MuiFormLabel-colorPrimary css-1t0alks"
                            data-shrink="false" for=":r0:" id=":r0:-label">Email</label>
                        <div class="MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-formControl css-8wv062">
                            <input aria-invalid="false" id=":r0:" type="email"
                                   class="MuiOutlinedInput-input MuiInputBase-input css-pv9vr9" value="">
                            <fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac">
                                <legend class="css-1ftyaf0"><span>Email</span></legend>
                            </fieldset>
                        </div>
                    </div>
                    <button class="MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-fullWidth MuiButtonBase-root  css-7pkcec"
                            tabindex="0" type="submit">Send reset link<span
                            class="MuiTouchRipple-root css-w0pj6f"></span></button>
                    <p class="MuiTypography-root MuiTypography-body1 css-1ylfc9m"><a
                            class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways MuiTypography-root MuiTypography-body1 css-1gd95cx"
                            href="{{ url_for('auth.signin') }}">
                        <svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-1usbx83" focusable="false"
                             aria-hidden="true" viewBox="0 0 24 24" data-testid="ChevronLeftIcon">
                            <path d="M15.41,16.58L10.83,12L15.41,7.41L14,6L8,12L14,18L15.41,16.58Z"></path>
                        </svg>
                        <span>Back to login</span></a></p>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

services/account/app/templates/signin.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}
{% block body %}
<div class="css-1bguz3s">
    <div class="content-center css-0">
        <div class="css-f615w0">
            <div class="css-dq7kpu">
                <div class="css-1vmv954">
                    <svg width="47" fill="none" height="26" viewBox="0 0 268 150"
                         xmlns="http://www.w3.org/2000/svg">
                        <rect rx="25.1443" width="50.2886" height="143.953" fill="#666CFF"
                              transform="matrix(-0.865206 0.501417 0.498585 0.866841 195.571 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill-opacity="0.4"
                              fill="url(#paint0_linear_7821_79167)"
                              transform="matrix(-0.865206 0.501417 0.498585 0.866841 196.084 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill="#666CFF"
                              transform="matrix(0.865206 0.501417 -0.498585 0.866841 173.147 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill="#666CFF"
                              transform="matrix(-0.865206 0.501417 0.498585 0.866841 94.1973 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill-opacity="0.4"
                              fill="url(#paint1_linear_7821_79167)"
                              transform="matrix(-0.865206 0.501417 0.498585 0.866841 94.1973 0)"></rect>
                        <rect rx="25.1443" width="50.2886" height="143.953" fill="#666CFF"
                              transform="matrix(0.865206 0.501417 -0.498585 0.866841 71.7728 0)"></rect>
                        <defs>
                            <linearGradient y1="0" x1="25.1443" x2="25.1443" y2="143.953"
                                            id="paint0_linear_7821_79167" gradientUnits="userSpaceOnUse">
                                <stop></stop>
                                <stop offset="1" stop-opacity="0"></stop>
                            </linearGradient>
                            <linearGradient y1="0" x1="25.1443" x2="25.1443" y2="143.953"
                                            id="paint1_linear_7821_79167" gradientUnits="userSpaceOnUse">
                                <stop></stop>
                                <stop offset="1" stop-opacity="0"></stop>
                            </linearGradient>
                        </defs>
                    </svg>
                    <h6 class="MuiTypography-root MuiTypography-h6 css-fjavz9">{{ config.DOMAIN|capitalize }}</h6>
                </div>
                <div class="MuiBox-root css-1fobf8d">
                    <h5 class="MuiTypography-root MuiTypography-h5 css-ya2iyo">
                        Welcome to {{ config.PROJECT_NAME|capitalize }}! 👋🏻</h5>
                    <p class="MuiTypography-root MuiTypography-body2 css-19cqx3h">Please sign-in to your account
                        and start the adventure</p>
                </div>
                <form novalidate="" autocomplete="off" method="post" action="{{ url_for('auth.signin') }}">
                    <div class="MuiFormControl-root MuiFormControl-fullWidth MuiTextField-root css-nbxxrn">
                        <label class="MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-outlined MuiFormLabel-root MuiFormLabel-colorPrimary css-1t0alks"
                               data-shrink="false" for="email" id="email-label">Email</label>
                        <div class="MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-fullWidth MuiInputBase-formControl css-13j0ouy">
                            <input aria-invalid="false" id="email" name="email" type="text"
                                   class="MuiOutlinedInput-input MuiInputBase-input css-pv9vr9" value="">
                            <fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac">
                                <legend class="css-1ftyaf0"><span>Email</span></legend>
                            </fieldset>
                        </div>
                    </div>
                    <div class="MuiFormControl-root MuiFormControl-fullWidth css-tzsjye"><label
                            class="MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-outlined MuiFormLabel-root MuiFormLabel-colorPrimary css-1t0alks"
                            data-shrink="false" for="auth-login-password">Password</label>
                        <div class="MuiOutlinedInput-root MuiInputBase-root MuiInputBase-colorPrimary MuiInputBase-formControl MuiInputBase-adornedEnd css-nhem73">
                            <input aria-invalid="false" id="auth-login-password" name="password" type="password"
                                   class="MuiOutlinedInput-input MuiInputBase-input MuiInputBase-inputAdornedEnd css-1jyh38l"
                                   value="">
                            <div class="MuiInputAdornment-root MuiInputAdornment-positionEnd MuiInputAdornment-outlined MuiInputAdornment-sizeMedium css-1aearad">
                                <button class="MuiButtonBase-root MuiIconButton-root MuiIconButton-edgeEnd MuiIconButton-sizeMedium css-1n5j0hu"
                                        tabindex="0" type="button" aria-label="toggle password visibility">
                                    <svg class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv"
                                         focusable="false" aria-hidden="true" viewBox="0 0 24 24"
                                         data-testid="EyeOffOutlineIcon">
                                        <path d="M2,5.27L3.28,4L20,20.72L18.73,22L15.65,18.92C14.5,19.3 13.28,19.5 12,19.5C7,19.5 2.73,16.39 1,12C1.69,10.24 2.79,8.69 4.19,7.46L2,5.27M12,9A3,3 0 0,1 15,12C15,12.35 14.94,12.69 14.83,13L11,9.17C11.31,9.06 11.65,9 12,9M12,4.5C17,4.5 21.27,7.61 23,12C22.18,14.08 20.79,15.88 19,17.19L17.58,15.76C18.94,14.82 20.06,13.54 20.82,12C19.17,8.64 15.76,6.5 12,6.5C10.91,6.5 9.84,6.68 8.84,7L7.3,5.47C8.74,4.85 10.33,4.5 12,4.5M3.18,12C4.83,15.36 8.24,17.5 12,17.5C12.69,17.5 13.37,17.43 14,17.29L11.72,15C10.29,14.85 9.15,13.71 9,12.28L5.6,8.87C4.61,9.72 3.78,10.78 3.18,12Z"></path>
                                    </svg>
                                    <span class="MuiTouchRipple-root css-w0pj6f"></span></button>
                            </div>
                            <fieldset aria-hidden="true" class="MuiOutlinedInput-notchedOutline css-igs3ac">
                                <legend class="css-1ftyaf0"><span>Password</span></legend>
                            </fieldset>
                        </div>
                    </div>
                    <div class="MuiBox-root css-1hb7t2u"><label
                            class="MuiFormControlLabel-root MuiFormControlLabel-labelPlacementEnd css-1dq2ezy"><span
                            class="MuiCheckbox-root MuiCheckbox-colorPrimary MuiButtonBase-root MuiCheckbox-root MuiCheckbox-colorPrimary PrivateSwitchBase-root css-1l36ixv"><input
                            class="PrivateSwitchBase-input css-1m9pwf3" type="checkbox"
                            data-indeterminate="false"><svg
                            class="MuiSvgIcon-root MuiSvgIcon-fontSizeMedium css-vubbuv" focusable="false"
                            aria-hidden="true" viewBox="0 0 24 24" data-testid="CheckBoxOutlineBlankIcon"><path
                            d="M19 5v14H5V5h14m0-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"></path></svg><span
                            class="MuiTouchRipple-root css-w0pj6f"></span></span><span
                            class="MuiTypography-root MuiTypography-body1 MuiFormControlLabel-label css-azsy9a">Remember Me</span></label><a
                            class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways MuiTypography-root MuiTypography-body2 css-lou2qq"
                            href="{{ url_for('auth.restore_password') }}">Forgot Password?</a></div>
                    <button class="MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-fullWidth MuiButtonBase-root  css-1g8zgnz"
                            tabindex="0" type="submit">Login<span class="MuiTouchRipple-root css-w0pj6f"></span>
                    </button>
                    <div class="MuiBox-root css-z0xj7h"><p
                            class="MuiTypography-root MuiTypography-body1 css-15up5iz">New on our platform?</p>
                        <p class="MuiTypography-root MuiTypography-body1 css-azsy9a"><a
                                class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways MuiTypography-root MuiTypography-body1 css-hmte51"
                                href="{{ url_for('auth.signup') }}">Create
                            an account</a>
                        </p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}